### ISSUE TITLE
'gbk' codec can't decode byte 0x8e in position 38: illegal multibyte sequence'gbk' codec can't decode byte 0x8e in position 38

### ISSUE THREAD

**Issue by thm1118** [shidenggui/easyhistory#17]
这其实不是easyhistory的错，是request包 内会读取本地用户目录的 .netrc或 _netrc文件内用户名和密码，试图自动完成网站认证过程，但是这个文件是utf8编码的，默认使用当前系统编码gbk去读取，就产生错误，在request项目内，关于 netrce的 [issure一大堆](https://github.com/kennethreitz/requests/issues?utf8=%E2%9C%93&q=netrc)，其中 [option to disable .netrc #2773](https://github.com/kennethreitz/requests/issues/2773)。

我现在暂时解决办法是，主动传入用户和密码，这样就不会读取netrc文件了，诸如：
 dom = PyQuery(url,  auth=('user', 'pass'))
 rep = requests.get(url, params, timeout=3, headers=headers, auth=('user', 'pass'))

官方似乎推荐设置 trust_env=false 来解决

**Comment by shidenggui** [comment]
easyhistory 放弃对 sina 数据的维护了
