### ISSUE TITLE
前复权调整问题

### ISSUE THREAD

**Issue by walkingsnail** [shidenggui/easyhistory#2]
前复权只需要对价格进行调整，不需要对成交量/额进行调整

以000039的4月1日数据为例，raw_data的成交量/额/复权因子如下：

17566666	264585488	23.302

data中对这两项都做了复权处理，结果如下，是错的：

753869.45	11354625.7	23.302

**Comment by njtian** [comment]
我觉得成交量应做调整，以保证公式“成交金额=价格*成交量”始终成立，不论前复权、后复权还是不复权。

**Comment by shidenggui** [comment]
更新了下，成交量不会被复权了。成交额还是应该根据复权缩减吧，否则 `成交金额 != 价格*成交量`

**Comment by walkingsnail** [comment]
是是是

**Comment by walkingsnail** [comment]
看股票软件好像都不调整的，你开个软件比较下，我一时没想清楚其中的关系
